---
label: Base
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: file
  name: icon
  label: icon
  description: homepage icon
- name: image
  type: file
  config:
    maxSize: 250
  label: image
pages:
- index.md
