---
label: project
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  hidden: true
- type: text
  name: title
  label: title
- type: text
  name: categories
  label: categories
  hidden: true
- type: text
  name: author
  label: author
- type: file
  name: icon
  label: icon
- type: text
  name: language
  label: language
  hidden: true
- name: lat
  type: number
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
  label: Pin Latitude
- name: lon
  type: number
  label: Pin Longitude
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
pages:
- _projects/kdekoli-mimo-svet.markdown
