---
label: project
hide_body: false
fields:
- name: image
  type: file
  config:
    maxSize: 250
  label: Main project image
  description: Every project have one cover image
- type: file
  name: icon
  label: icon
- name: name
  type: text
  config:
    required: false
  label: name
- type: text
  name: title
  label: url
- name: lat
  type: number
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
  label: Pin Latitude
- name: lon
  type: number
  label: Pin Longitude
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- type: text
  name: author
  label: author
- name: excerpt
  type: text
  config:
    required: false
  label: excerpt
- type: text
  name: categories
  label: categories
  hidden: true
- type: text
  name: language
  label: language
  hidden: true
  default: sk
- type: text
  name: layout
  label: layout
  hidden: true
  default: post
pages:
- _projects/komunitne-centrum-velky-krtis.md
- _projects/zmes-urbanneho-a-virtuálneho.md
- _projects/kdekolvek-mimo-svet.md
- _projects/sidlisko-a-rozcestnik.md
- _projects/statut-mesta.md
- _projects/pocuvaj-ma-sem.md
- _projects/obalky-a-pasky.md
- _projects/pohyb-zhromazdenie-a-jaho-rozklad.md
